name: Continuous Integration
on: [push, pull_request, release]
jobs:
  nodejs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run-script buildLint
    - run: npm run-script buildTypeScript
    - run: npm run-script buildNyc
